/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Public;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records.CurrentReservationsRecord;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CurrentReservations extends TableImpl<CurrentReservationsRecord> {

	private static final long serialVersionUID = 1723371998;

	/**
	 * The reference instance of <code>public.current_reservations</code>
	 */
	public static final CurrentReservations CURRENT_RESERVATIONS = new CurrentReservations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CurrentReservationsRecord> getRecordType() {
		return CurrentReservationsRecord.class;
	}

	/**
	 * The column <code>public.current_reservations.id</code>.
	 */
	public final TableField<CurrentReservationsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.current_reservations.machine_id</code>.
	 */
	public final TableField<CurrentReservationsRecord, Short> MACHINE_ID = createField("machine_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.current_reservations.client_id</code>.
	 */
	public final TableField<CurrentReservationsRecord, Short> CLIENT_ID = createField("client_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.current_reservations.requested_at</code>.
	 */
	public final TableField<CurrentReservationsRecord, Timestamp> REQUESTED_AT = createField("requested_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.current_reservations.locked_at</code>.
	 */
	public final TableField<CurrentReservationsRecord, Timestamp> LOCKED_AT = createField("locked_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.current_reservations.unlocked_at</code>.
	 */
	public final TableField<CurrentReservationsRecord, Timestamp> UNLOCKED_AT = createField("unlocked_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.current_reservations.is_canceled</code>.
	 */
	public final TableField<CurrentReservationsRecord, Boolean> IS_CANCELED = createField("is_canceled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.current_reservations</code> table reference
	 */
	public CurrentReservations() {
		this("current_reservations", null);
	}

	/**
	 * Create an aliased <code>public.current_reservations</code> table reference
	 */
	public CurrentReservations(String alias) {
		this(alias, CURRENT_RESERVATIONS);
	}

	private CurrentReservations(String alias, Table<CurrentReservationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private CurrentReservations(String alias, Table<CurrentReservationsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CurrentReservations as(String alias) {
		return new CurrentReservations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public CurrentReservations rename(String name) {
		return new CurrentReservations(name, null);
	}
}
