/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Public;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records.EffectiveReservationsRecord;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EffectiveReservations extends TableImpl<EffectiveReservationsRecord> {

	private static final long serialVersionUID = -915571040;

	/**
	 * The reference instance of <code>public.effective_reservations</code>
	 */
	public static final EffectiveReservations EFFECTIVE_RESERVATIONS = new EffectiveReservations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EffectiveReservationsRecord> getRecordType() {
		return EffectiveReservationsRecord.class;
	}

	/**
	 * The column <code>public.effective_reservations.id</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.effective_reservations.machine_id</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Short> MACHINE_ID = createField("machine_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.effective_reservations.client_id</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Short> CLIENT_ID = createField("client_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.effective_reservations.requested_at</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Timestamp> REQUESTED_AT = createField("requested_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.effective_reservations.locked_at</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Timestamp> LOCKED_AT = createField("locked_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.effective_reservations.unlocked_at</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Timestamp> UNLOCKED_AT = createField("unlocked_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.effective_reservations.is_canceled</code>.
	 */
	public final TableField<EffectiveReservationsRecord, Boolean> IS_CANCELED = createField("is_canceled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.effective_reservations</code> table reference
	 */
	public EffectiveReservations() {
		this("effective_reservations", null);
	}

	/**
	 * Create an aliased <code>public.effective_reservations</code> table reference
	 */
	public EffectiveReservations(String alias) {
		this(alias, EFFECTIVE_RESERVATIONS);
	}

	private EffectiveReservations(String alias, Table<EffectiveReservationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private EffectiveReservations(String alias, Table<EffectiveReservationsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EffectiveReservations as(String alias) {
		return new EffectiveReservations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EffectiveReservations rename(String name) {
		return new EffectiveReservations(name, null);
	}
}
