/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Keys;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Public;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records.MachineModelsRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineModels extends TableImpl<MachineModelsRecord> {

	private static final long serialVersionUID = -411641361;

	/**
	 * The reference instance of <code>public.machine_models</code>
	 */
	public static final MachineModels MACHINE_MODELS = new MachineModels();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MachineModelsRecord> getRecordType() {
		return MachineModelsRecord.class;
	}

	/**
	 * The column <code>public.machine_models.id</code>.
	 */
	public final TableField<MachineModelsRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.machine_models.manufacturer_id</code>.
	 */
	public final TableField<MachineModelsRecord, Short> MANUFACTURER_ID = createField("manufacturer_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * The column <code>public.machine_models.code</code>.
	 */
	public final TableField<MachineModelsRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>public.machine_models</code> table reference
	 */
	public MachineModels() {
		this("machine_models", null);
	}

	/**
	 * Create an aliased <code>public.machine_models</code> table reference
	 */
	public MachineModels(String alias) {
		this(alias, MACHINE_MODELS);
	}

	private MachineModels(String alias, Table<MachineModelsRecord> aliased) {
		this(alias, aliased, null);
	}

	private MachineModels(String alias, Table<MachineModelsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<MachineModelsRecord, Short> getIdentity() {
		return Keys.IDENTITY_MACHINE_MODELS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MachineModelsRecord> getPrimaryKey() {
		return Keys.MACHINE_MODELS_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MachineModelsRecord>> getKeys() {
		return Arrays.<UniqueKey<MachineModelsRecord>>asList(Keys.MACHINE_MODELS_PKEY, Keys.MACHINE_MODELS_CODE_KEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<MachineModelsRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<MachineModelsRecord, ?>>asList(Keys.MACHINE_MODELS__MACHINE_MODELS_MANUFACTURER_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineModels as(String alias) {
		return new MachineModels(alias, this);
	}

	/**
	 * Rename this table
	 */
	public MachineModels rename(String name) {
		return new MachineModels(name, null);
	}
}
