/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Keys;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Public;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records.MachinesRecord;

import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Machines extends TableImpl<MachinesRecord> {

	private static final long serialVersionUID = 548411064;

	/**
	 * The reference instance of <code>public.machines</code>
	 */
	public static final Machines MACHINES = new Machines();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<MachinesRecord> getRecordType() {
		return MachinesRecord.class;
	}

	/**
	 * The column <code>public.machines.id</code>.
	 */
	public final TableField<MachinesRecord, Short> ID = createField("id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.machines.model_id</code>.
	 */
	public final TableField<MachinesRecord, Short> MODEL_ID = createField("model_id", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "");

	/**
	 * Create a <code>public.machines</code> table reference
	 */
	public Machines() {
		this("machines", null);
	}

	/**
	 * Create an aliased <code>public.machines</code> table reference
	 */
	public Machines(String alias) {
		this(alias, MACHINES);
	}

	private Machines(String alias, Table<MachinesRecord> aliased) {
		this(alias, aliased, null);
	}

	private Machines(String alias, Table<MachinesRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<MachinesRecord, Short> getIdentity() {
		return Keys.IDENTITY_MACHINES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<MachinesRecord> getPrimaryKey() {
		return Keys.MACHINES_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<MachinesRecord>> getKeys() {
		return Arrays.<UniqueKey<MachinesRecord>>asList(Keys.MACHINES_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<MachinesRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<MachinesRecord, ?>>asList(Keys.MACHINES__MACHINES_MODEL_ID_FKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Machines as(String alias) {
		return new Machines(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Machines rename(String name) {
		return new Machines(name, null);
	}
}
