/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.Public;
import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records.ReservationsRecord;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reservations extends TableImpl<ReservationsRecord> {

	private static final long serialVersionUID = 2117079682;

	/**
	 * The reference instance of <code>public.reservations</code>
	 */
	public static final Reservations RESERVATIONS = new Reservations();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReservationsRecord> getRecordType() {
		return ReservationsRecord.class;
	}

	/**
	 * The column <code>public.reservations.id</code>.
	 */
	public final TableField<ReservationsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.reservations.machine_id</code>.
	 */
	public final TableField<ReservationsRecord, Short> MACHINE_ID = createField("machine_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.reservations.client_id</code>.
	 */
	public final TableField<ReservationsRecord, Short> CLIENT_ID = createField("client_id", org.jooq.impl.SQLDataType.SMALLINT, this, "");

	/**
	 * The column <code>public.reservations.requested_at</code>.
	 */
	public final TableField<ReservationsRecord, Timestamp> REQUESTED_AT = createField("requested_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.reservations.locked_at</code>.
	 */
	public final TableField<ReservationsRecord, Timestamp> LOCKED_AT = createField("locked_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.reservations.unlocked_at</code>.
	 */
	public final TableField<ReservationsRecord, Timestamp> UNLOCKED_AT = createField("unlocked_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.reservations.is_canceled</code>.
	 */
	public final TableField<ReservationsRecord, Boolean> IS_CANCELED = createField("is_canceled", org.jooq.impl.SQLDataType.BOOLEAN, this, "");

	/**
	 * Create a <code>public.reservations</code> table reference
	 */
	public Reservations() {
		this("reservations", null);
	}

	/**
	 * Create an aliased <code>public.reservations</code> table reference
	 */
	public Reservations(String alias) {
		this(alias, RESERVATIONS);
	}

	private Reservations(String alias, Table<ReservationsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Reservations(String alias, Table<ReservationsRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Reservations as(String alias) {
		return new Reservations(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Reservations rename(String name) {
		return new Reservations(name, null);
	}
}
