/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.AvailableMachines;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AvailableMachinesRecord extends TableRecordImpl<AvailableMachinesRecord> implements Record3<Short, Short, Long> {

	private static final long serialVersionUID = 1545715384;

	/**
	 * Setter for <code>public.available_machines.id</code>.
	 */
	public void setId(Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.available_machines.id</code>.
	 */
	public Short getId() {
		return (Short) getValue(0);
	}

	/**
	 * Setter for <code>public.available_machines.model_id</code>.
	 */
	public void setModelId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.available_machines.model_id</code>.
	 */
	public Short getModelId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>public.available_machines.load</code>.
	 */
	public void setLoad(Long value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.available_machines.load</code>.
	 */
	public Long getLoad() {
		return (Long) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Short, Short, Long> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<Short, Short, Long> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field1() {
		return AvailableMachines.AVAILABLE_MACHINES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return AvailableMachines.AVAILABLE_MACHINES.MODEL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Long> field3() {
		return AvailableMachines.AVAILABLE_MACHINES.LOAD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getModelId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Long value3() {
		return getLoad();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvailableMachinesRecord value1(Short value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvailableMachinesRecord value2(Short value) {
		setModelId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvailableMachinesRecord value3(Long value) {
		setLoad(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AvailableMachinesRecord values(Short value1, Short value2, Long value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AvailableMachinesRecord
	 */
	public AvailableMachinesRecord() {
		super(AvailableMachines.AVAILABLE_MACHINES);
	}

	/**
	 * Create a detached, initialised AvailableMachinesRecord
	 */
	public AvailableMachinesRecord(Short id, Short modelId, Long load) {
		super(AvailableMachines.AVAILABLE_MACHINES);

		setValue(0, id);
		setValue(1, modelId);
		setValue(2, load);
	}
}
