/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.MachineComebacks;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineComebacksRecord extends UpdatableRecordImpl<MachineComebacksRecord> implements Record2<Short, Timestamp> {

	private static final long serialVersionUID = -569416070;

	/**
	 * Setter for <code>public.machine_comebacks.failure_id</code>.
	 */
	public void setFailureId(Short value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.machine_comebacks.failure_id</code>.
	 */
	public Short getFailureId() {
		return (Short) getValue(0);
	}

	/**
	 * Setter for <code>public.machine_comebacks.occured_at</code>.
	 */
	public void setOccuredAt(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.machine_comebacks.occured_at</code>.
	 */
	public Timestamp getOccuredAt() {
		return (Timestamp) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Short> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Short, Timestamp> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Short, Timestamp> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field1() {
		return MachineComebacks.MACHINE_COMEBACKS.FAILURE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return MachineComebacks.MACHINE_COMEBACKS.OCCURED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value1() {
		return getFailureId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getOccuredAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineComebacksRecord value1(Short value) {
		setFailureId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineComebacksRecord value2(Timestamp value) {
		setOccuredAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public MachineComebacksRecord values(Short value1, Timestamp value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached MachineComebacksRecord
	 */
	public MachineComebacksRecord() {
		super(MachineComebacks.MACHINE_COMEBACKS);
	}

	/**
	 * Create a detached, initialised MachineComebacksRecord
	 */
	public MachineComebacksRecord(Short failureId, Timestamp occuredAt) {
		super(MachineComebacks.MACHINE_COMEBACKS);

		setValue(0, failureId);
		setValue(1, occuredAt);
	}
}
