/**
 * This class is generated by jOOQ
 */
package ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.records;


import ch.protonmail.vladyslavbond.washing_scheduler.datasource.tables.Requests;

import java.sql.Timestamp;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestsRecord extends UpdatableRecordImpl<RequestsRecord> implements Record6<Integer, Short, Short, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = -492978573;

	/**
	 * Setter for <code>public.requests.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.requests.id</code>.
	 */
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.requests.machine_id</code>.
	 */
	public void setMachineId(Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.requests.machine_id</code>.
	 */
	public Short getMachineId() {
		return (Short) getValue(1);
	}

	/**
	 * Setter for <code>public.requests.client_id</code>.
	 */
	public void setClientId(Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.requests.client_id</code>.
	 */
	public Short getClientId() {
		return (Short) getValue(2);
	}

	/**
	 * Setter for <code>public.requests.requested_at</code>.
	 */
	public void setRequestedAt(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.requests.requested_at</code>.
	 */
	public Timestamp getRequestedAt() {
		return (Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.requests.locked_at</code>.
	 */
	public void setLockedAt(Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.requests.locked_at</code>.
	 */
	public Timestamp getLockedAt() {
		return (Timestamp) getValue(4);
	}

	/**
	 * Setter for <code>public.requests.unlocked_at</code>.
	 */
	public void setUnlockedAt(Timestamp value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.requests.unlocked_at</code>.
	 */
	public Timestamp getUnlockedAt() {
		return (Timestamp) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Short, Short, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Short, Short, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Requests.REQUESTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field2() {
		return Requests.REQUESTS.MACHINE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Short> field3() {
		return Requests.REQUESTS.CLIENT_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Requests.REQUESTS.REQUESTED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Requests.REQUESTS.LOCKED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Requests.REQUESTS.UNLOCKED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value2() {
		return getMachineId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Short value3() {
		return getClientId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getRequestedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getLockedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getUnlockedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord value2(Short value) {
		setMachineId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord value3(Short value) {
		setClientId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord value4(Timestamp value) {
		setRequestedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord value5(Timestamp value) {
		setLockedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord value6(Timestamp value) {
		setUnlockedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RequestsRecord values(Integer value1, Short value2, Short value3, Timestamp value4, Timestamp value5, Timestamp value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RequestsRecord
	 */
	public RequestsRecord() {
		super(Requests.REQUESTS);
	}

	/**
	 * Create a detached, initialised RequestsRecord
	 */
	public RequestsRecord(Integer id, Short machineId, Short clientId, Timestamp requestedAt, Timestamp lockedAt, Timestamp unlockedAt) {
		super(Requests.REQUESTS);

		setValue(0, id);
		setValue(1, machineId);
		setValue(2, clientId);
		setValue(3, requestedAt);
		setValue(4, lockedAt);
		setValue(5, unlockedAt);
	}
}
